FROM python:3.11-slim

# Устанавливаем Poetry
RUN pip install poetry

# Настраиваем Poetry
ENV POETRY_NO_INTERACTION=1 \
    POETRY_VENV_IN_PROJECT=1 \
    POETRY_CACHE_DIR=/tmp/poetry_cache

WORKDIR /app

# Копируем файлы конфигурации Poetry
COPY pyproject.toml poetry.lock* ./

# Устанавливаем зависимости
RUN poetry install --only=main && rm -rf $POETRY_CACHE_DIR

# Копируем исходный код
COPY . .

# Запускаем бота
CMD ["poetry", "run", "python", "main.py"]